
BLOCKSIZE = 32000
INPUTFILE = "map.osm"
DATAFILE = "data.xml"
INDEXFILE = "index.xml"

FILEHEADER = """
<header>
<type>{0}</type>
<records>0</records>
<lastrecord>0</lastrecord>
</header>
"""

NUM_OF_COORDINATES = 2
COORDINATE_SIZE = 14
COORDINATES_INDEX_SIZE = len(str(NUM_OF_COORDINATES))

RECORD_BLOCK_ID_SIZE = 5
RECORD_SLOT_INDEX_SIZE = 4

NODE_ID_SIZE = 5
NODE_SLOT_INDEX_SIZE = 4
NODE_ENTRIES_NUM = 10 ** NODE_SLOT_INDEX_SIZE

NODE_MIN_ENTRIES = NODE_ENTRIES_NUM // 2

POINT_NAME_SIZE = 32
POINT_ID_SIZE = 10